import './style.css'

type Applicant = { documentNumber: string; email: string }
const app = document.querySelector<HTMLDivElement>('#app')!
const accountStorageKey = 'unac-applicants'

app.innerHTML = `
  <header class="topbar"><a class="brand" href="/" aria-label="UNAC, inicio"><span class="brand-mark" aria-hidden="true">A</span><span>UNAC</span></a><div class="topbar-context"><span class="secure-dot" aria-hidden="true"></span>Portal seguro de admisiones</div></header>
  <main class="page-shell"><nav class="breadcrumbs" aria-label="Miga de pan"><a href="/">Inicio</a><span aria-hidden="true">/</span><strong>Crear cuenta</strong></nav>
    <div class="content-grid"><section class="form-column"><div class="intro"><span class="eyebrow">Paso 1 de 3</span><h1>Crea tu cuenta de aspirante</h1><p>Registra tus datos para iniciar tu proceso de inscripci&oacute;n a la UNAC.</p></div>
      <form id="registration-form" novalidate><div class="section-heading"><span>01</span><div><h2>Datos personales</h2><p>Cu&eacute;ntanos c&oacute;mo podemos identificarte.</p></div></div>
        <div class="form-grid"><label>Nombre<input name="firstName" autocomplete="given-name" placeholder="Ej. Mar&iacute;a" required><small class="field-error"></small></label><label>Apellidos<input name="lastName" autocomplete="family-name" placeholder="Ej. Gonz&aacute;lez Rojas" required><small class="field-error"></small></label><label>Tipo de documento<select name="documentType" required><option value="">Selecciona una opci&oacute;n</option><option value="CC">C&eacute;dula de ciudadan&iacute;a</option><option value="TI">Tarjeta de identidad</option><option value="CE">C&eacute;dula de extranjer&iacute;a</option><option value="PAS">Pasaporte</option></select><small class="field-error"></small></label><label>N&uacute;mero de documento<input name="documentNumber" inputmode="numeric" autocomplete="off" placeholder="Ej. 1020304050" required><small class="field-error"></small></label><label>Correo electr&oacute;nico<input name="email" type="email" autocomplete="email" placeholder="nombre@correo.com" required><small class="field-error"></small></label><label>Tel&eacute;fono<input name="phone" type="tel" inputmode="tel" autocomplete="tel" placeholder="Ej. 300 123 4567" required><small class="field-error"></small></label></div>
        <div class="section-heading credentials-heading"><span>02</span><div><h2>Crea tu contrase&ntilde;a</h2><p>Usar&aacute;s estos datos para ingresar al portal.</p></div></div><div class="form-grid password-grid"><label>Contrase&ntilde;a<input name="password" type="password" autocomplete="new-password" placeholder="M&iacute;nimo 8 caracteres" required><small class="field-error"></small></label><label>Confirmar contrase&ntilde;a<input name="confirmPassword" type="password" autocomplete="new-password" placeholder="Repite tu contrase&ntilde;a" required><small class="field-error"></small></label></div>
        <div class="password-hint"><span class="hint-icon" aria-hidden="true">i</span><span>Debe tener al menos 8 caracteres, una may&uacute;scula, una min&uacute;scula y un n&uacute;mero.</span></div><div id="form-message" class="form-message" role="status" aria-live="polite"></div><div class="form-footer"><p>Al continuar aceptas el tratamiento de tus datos personales.</p><button type="submit">Crear cuenta <span aria-hidden="true">&#8594;</span></button></div>
      </form></section>
      <aside class="side-panel"><div class="aside-illustration" aria-hidden="true"><span class="sun"></span><span class="illustration-person">&#9786;</span><span class="illustration-card"></span></div><h2>Tu proceso comienza aqu&iacute;</h2><p>Completa tu registro y podr&aacute;s continuar con tu solicitud de admisi&oacute;n.</p><div class="progress-list"><div class="progress-item active"><span>1</span><div><strong>Crear cuenta</strong><small>Datos del aspirante</small></div></div><div class="progress-item"><span>2</span><div><strong>Inscripci&oacute;n</strong><small>Elige tu programa</small></div></div><div class="progress-item"><span>3</span><div><strong>Seguimiento</strong><small>Consulta el estado</small></div></div></div><div class="help-box"><span aria-hidden="true">?</span><p><strong>&iquest;Necesitas ayuda?</strong><br>Estamos aqu&iacute; para orientarte.</p></div></aside>
    </div></main><footer><span>&copy; 2026 UNAC</span><span>Admisiones <b aria-hidden="true">&bull;</b> Privacidad</span></footer>`

function getApplicants(): Applicant[] { try { return JSON.parse(localStorage.getItem(accountStorageKey) ?? '[]') as Applicant[] } catch { return [] } }
function setError(field: HTMLInputElement | HTMLSelectElement, text: string): void { field.classList.toggle('invalid', Boolean(text)); field.setAttribute('aria-invalid', String(Boolean(text))); const error = field.parentElement?.querySelector<HTMLElement>('.field-error'); if (error) error.textContent = text }

const form = document.querySelector<HTMLFormElement>('#registration-form')!
const message = document.querySelector<HTMLDivElement>('#form-message')!
form.addEventListener('submit', (event) => { event.preventDefault(); message.className = 'form-message'; message.textContent = ''; const data = new FormData(form); const names = ['firstName', 'lastName', 'documentType', 'documentNumber', 'email', 'phone', 'password', 'confirmPassword']; let valid = true; names.forEach((name) => { const field = form.elements.namedItem(name) as HTMLInputElement | HTMLSelectElement; const error = field.value.trim() ? '' : 'Este campo es obligatorio.'; setError(field, error); valid = valid && !error }); const email = String(data.get('email')).trim().toLowerCase(); const documentNumber = String(data.get('documentNumber')).trim(); const password = String(data.get('password')); const confirmPassword = String(data.get('confirmPassword')); const applicants = getApplicants(); const emailField = form.elements.namedItem('email') as HTMLInputElement; const documentField = form.elements.namedItem('documentNumber') as HTMLInputElement; const passwordField = form.elements.namedItem('password') as HTMLInputElement; const confirmField = form.elements.namedItem('confirmPassword') as HTMLInputElement; if (emailField.value && !emailField.validity.valid) { setError(emailField, 'Ingresa un correo electronico valido.'); valid = false } if (applicants.some((applicant) => applicant.email === email)) { setError(emailField, 'Este correo ya esta registrado.'); valid = false } if (applicants.some((applicant) => applicant.documentNumber === documentNumber)) { setError(documentField, 'Este documento ya esta registrado.'); valid = false } if (password && !/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/.test(password)) { setError(passwordField, 'La contrasena no cumple los requisitos.'); valid = false } if (password && confirmPassword && password !== confirmPassword) { setError(confirmField, 'Las contrasenas no coinciden.'); valid = false } if (!valid) { message.className = 'form-message error'; message.textContent = 'Revisa los campos marcados para continuar.'; return } applicants.push({ email, documentNumber }); localStorage.setItem(accountStorageKey, JSON.stringify(applicants)); form.reset(); message.className = 'form-message success'; message.innerHTML = '<strong>&#10003; Registro exitoso.</strong> Tu cuenta de aspirante ha sido creada correctamente.' })
